// File generated by FlutterFire CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKs_CKFJCQBVRX9jyPAhLufnAkyYnvUxs',
    appId: '1:57208501982:web:319701bc7dcad04b8eb44f',
    messagingSenderId: '57208501982',
    projectId: 'smartvendingmachine-2e3f8',
    authDomain: 'smartvendingmachine-2e3f8.firebaseapp.com',
    databaseURL: 'https://smartvendingmachine-2e3f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartvendingmachine-2e3f8.firebasestorage.app',
    measurementId: 'G-MR4EBQG21R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6DwS5tPCNZMu_NpEEQ16zACy9qa0F9Sk',
    appId: '1:57208501982:android:b62f9d01e0bff50c8eb44f',
    messagingSenderId: '57208501982',
    projectId: 'smartvendingmachine-2e3f8',
    databaseURL: 'https://smartvendingmachine-2e3f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartvendingmachine-2e3f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQdpwH-A9LKmJWGLQT28b3IfUx47pDHys',
    appId: '1:57208501982:ios:33155c9b45b80d778eb44f',
    messagingSenderId: '57208501982',
    projectId: 'smartvendingmachine-2e3f8',
    databaseURL: 'https://smartvendingmachine-2e3f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartvendingmachine-2e3f8.firebasestorage.app',
    iosBundleId: 'com.example.smartVending',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQdpwH-A9LKmJWGLQT28b3IfUx47pDHys',
    appId: '1:57208501982:ios:33155c9b45b80d778eb44f',
    messagingSenderId: '57208501982',
    projectId: 'smartvendingmachine-2e3f8',
    databaseURL: 'https://smartvendingmachine-2e3f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartvendingmachine-2e3f8.firebasestorage.app',
    iosBundleId: 'com.example.smartVending',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKs_CKFJCQBVRX9jyPAhLufnAkyYnvUxs',
    appId: '1:57208501982:web:16351f07daa830138eb44f',
    messagingSenderId: '57208501982',
    projectId: 'smartvendingmachine-2e3f8',
    authDomain: 'smartvendingmachine-2e3f8.firebaseapp.com',
    databaseURL: 'https://smartvendingmachine-2e3f8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smartvendingmachine-2e3f8.firebasestorage.app',
    measurementId: 'G-F9BC85QP8M',
  );
}
